"""Planificacion tenant de personas sin fichaje ni liquidacion salarial."""
from sqlalchemy import CheckConstraint,UniqueConstraint
from extensions import db
from services.fechas import ahora_utc_naive

class TurnoLaboralPlanificado(db.Model):
    __tablename__="turno_laboral_planificado"
    __table_args__=(UniqueConstraint("organizacion_id","clave_idempotencia",name="uq_turno_laboral_clave"),CheckConstraint("fin > inicio",name="ck_turno_laboral_fechas"),CheckConstraint("estado IN ('planificado','cancelado')",name="ck_turno_laboral_estado"),CheckConstraint("confirmado = false AND afecta_nomina = false",name="ck_turno_laboral_sin_impacto"),)
    id=db.Column(db.Integer,primary_key=True);organizacion_id=db.Column(db.Integer,db.ForeignKey("organizacion.id"),nullable=False,index=True);unidad_negocio_id=db.Column(db.Integer,db.ForeignKey("unidad_negocio.id"),nullable=False,index=True);empleado_id=db.Column(db.Integer,db.ForeignKey("empleado_productivo.id"),nullable=False,index=True)
    inicio=db.Column(db.DateTime,nullable=False,index=True);fin=db.Column(db.DateTime,nullable=False,index=True);sector=db.Column(db.String(120),nullable=False);tarea=db.Column(db.String(240));clave_idempotencia=db.Column(db.String(180),nullable=False);estado=db.Column(db.String(20),default="planificado",nullable=False,index=True);confirmado=db.Column(db.Boolean,default=False,nullable=False);afecta_nomina=db.Column(db.Boolean,default=False,nullable=False);observacion=db.Column(db.String(500));creado_por_usuario_id=db.Column(db.Integer,db.ForeignKey("usuario_sistema.id"));fecha_creacion=db.Column(db.DateTime,default=ahora_utc_naive,nullable=False);empleado=db.relationship("EmpleadoProductivo")

class NovedadLaboralPreparatoria(db.Model):
    __tablename__="novedad_laboral_preparatoria"
    __table_args__=(UniqueConstraint("organizacion_id","clave_idempotencia",name="uq_novedad_laboral_clave"),CheckConstraint("tipo IN ('licencia','ausencia','horas_extra','observacion')",name="ck_novedad_laboral_tipo"),CheckConstraint("fecha_hasta >= fecha_desde",name="ck_novedad_laboral_fechas"),CheckConstraint("estado IN ('propuesta','cancelada')",name="ck_novedad_laboral_estado"),CheckConstraint("aprobada = false AND afecta_nomina = false",name="ck_novedad_laboral_sin_impacto"),)
    id=db.Column(db.Integer,primary_key=True);organizacion_id=db.Column(db.Integer,db.ForeignKey("organizacion.id"),nullable=False,index=True);unidad_negocio_id=db.Column(db.Integer,db.ForeignKey("unidad_negocio.id"),nullable=False,index=True);empleado_id=db.Column(db.Integer,db.ForeignKey("empleado_productivo.id"),nullable=False,index=True)
    tipo=db.Column(db.String(20),nullable=False,index=True);fecha_desde=db.Column(db.Date,nullable=False,index=True);fecha_hasta=db.Column(db.Date,nullable=False,index=True);detalle=db.Column(db.String(500),nullable=False);minutos_propuestos=db.Column(db.Integer,default=0,nullable=False);clave_idempotencia=db.Column(db.String(180),nullable=False);estado=db.Column(db.String(20),default="propuesta",nullable=False,index=True);aprobada=db.Column(db.Boolean,default=False,nullable=False);afecta_nomina=db.Column(db.Boolean,default=False,nullable=False);observacion=db.Column(db.String(500));creado_por_usuario_id=db.Column(db.Integer,db.ForeignKey("usuario_sistema.id"));fecha_creacion=db.Column(db.DateTime,default=ahora_utc_naive,nullable=False);empleado=db.relationship("EmpleadoProductivo")

class CompetenciaEmpleadoPreparatoria(db.Model):
    __tablename__="competencia_empleado_preparatoria"
    __table_args__=(UniqueConstraint("empleado_id","codigo",name="uq_competencia_empleado_codigo"),CheckConstraint("nivel >= 1 AND nivel <= 5",name="ck_competencia_nivel"),CheckConstraint("verificada = false AND habilita_asignacion = false",name="ck_competencia_no_habilitante"),)
    id=db.Column(db.Integer,primary_key=True);organizacion_id=db.Column(db.Integer,db.ForeignKey("organizacion.id"),nullable=False,index=True);unidad_negocio_id=db.Column(db.Integer,db.ForeignKey("unidad_negocio.id"),nullable=False,index=True);empleado_id=db.Column(db.Integer,db.ForeignKey("empleado_productivo.id"),nullable=False,index=True)
    codigo=db.Column(db.String(80),nullable=False);nombre=db.Column(db.String(180),nullable=False);nivel=db.Column(db.Integer,nullable=False);vence_el=db.Column(db.Date,index=True);verificada=db.Column(db.Boolean,default=False,nullable=False);habilita_asignacion=db.Column(db.Boolean,default=False,nullable=False);observacion=db.Column(db.String(500));fecha_creacion=db.Column(db.DateTime,default=ahora_utc_naive,nullable=False);empleado=db.relationship("EmpleadoProductivo")
