"""Casos y propuestas preparatorias de postventa sin efectos externos."""
from sqlalchemy import CheckConstraint,UniqueConstraint
from extensions import db
from services.fechas import ahora_utc_naive
class CasoPostventa(db.Model):
 __tablename__="caso_postventa";__table_args__=(UniqueConstraint("organizacion_id","clave_idempotencia",name="uq_caso_postventa_clave"),CheckConstraint("tipo IN ('devolucion','garantia','reclamo','cambio')",name="ck_caso_postventa_tipo"),CheckConstraint("estado IN ('abierto','diagnostico','propuesta','cerrado_sin_efecto','cancelado')",name="ck_caso_postventa_estado"),CheckConstraint("contacto_externo = false AND afecta_stock = false AND afecta_saldo = false",name="ck_caso_postventa_sin_impacto"),)
 id=db.Column(db.Integer,primary_key=True);organizacion_id=db.Column(db.Integer,db.ForeignKey("organizacion.id"),nullable=False,index=True);unidad_negocio_id=db.Column(db.Integer,db.ForeignKey("unidad_negocio.id"),nullable=False,index=True);pedido_id=db.Column(db.Integer,db.ForeignKey("pedido.id"),nullable=False,index=True);tipo=db.Column(db.String(20),nullable=False,index=True);titulo=db.Column(db.String(180),nullable=False);descripcion=db.Column(db.String(1000),nullable=False);clave_idempotencia=db.Column(db.String(180),nullable=False);estado=db.Column(db.String(30),default="abierto",nullable=False,index=True);contacto_externo=db.Column(db.Boolean,default=False,nullable=False);afecta_stock=db.Column(db.Boolean,default=False,nullable=False);afecta_saldo=db.Column(db.Boolean,default=False,nullable=False);creado_por_usuario_id=db.Column(db.Integer,db.ForeignKey("usuario_sistema.id"));fecha_creacion=db.Column(db.DateTime,default=ahora_utc_naive,nullable=False);pedido=db.relationship("Pedido")
class PropuestaResolucionPostventa(db.Model):
 __tablename__="propuesta_resolucion_postventa";__table_args__=(UniqueConstraint("caso_id","tipo",name="uq_resolucion_postventa_tipo"),CheckConstraint("tipo IN ('reposicion','reintegro','reparacion','cambio','rechazo')",name="ck_resolucion_postventa_tipo"),CheckConstraint("importe_centavos >= 0",name="ck_resolucion_postventa_importe"),CheckConstraint("aprobada = false AND ejecutada = false AND afecta_stock = false AND emite_credito = false",name="ck_resolucion_postventa_sin_impacto"),)
 id=db.Column(db.Integer,primary_key=True);organizacion_id=db.Column(db.Integer,db.ForeignKey("organizacion.id"),nullable=False,index=True);unidad_negocio_id=db.Column(db.Integer,db.ForeignKey("unidad_negocio.id"),nullable=False,index=True);caso_id=db.Column(db.Integer,db.ForeignKey("caso_postventa.id"),nullable=False,index=True);tipo=db.Column(db.String(20),nullable=False);detalle=db.Column(db.String(800),nullable=False);importe_centavos=db.Column(db.BigInteger,default=0,nullable=False);aprobada=db.Column(db.Boolean,default=False,nullable=False);ejecutada=db.Column(db.Boolean,default=False,nullable=False);afecta_stock=db.Column(db.Boolean,default=False,nullable=False);emite_credito=db.Column(db.Boolean,default=False,nullable=False);fecha_creacion=db.Column(db.DateTime,default=ahora_utc_naive,nullable=False);caso=db.relationship("CasoPostventa",backref="propuestas")
